-- ============================================================
-- Credit Payment Terms, Partial Payments & Due Alerts
-- Migration for existing Supabase databases.
-- Run this in the Supabase SQL Editor.
-- Safe to re-run (idempotent).
-- ============================================================

-- 1. Credit terms on purchases -------------------------------
alter table purchases add column if not exists credit_period_days integer;
alter table purchases add column if not exists due_date date;
create index if not exists idx_purchases_due on purchases(due_date);

-- 2. Direct payment ledger (cash / cheque / bank transfer) ----
--    Recorded straight against a purchase, independent of the
--    formal Cheques module. paid = these payments + cheque allocations.
create table if not exists purchase_payments (
  id integer generated by default as identity primary key,
  purchase_id integer not null references purchases(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  method text not null default 'cash' check (method in ('cash','cheque','bank_transfer')),
  reference text,
  paid_on date not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_pp_purchase on purchase_payments(purchase_id);

-- 3. Guard table so a purchase due reminder is never sent twice
create table if not exists purchase_alerts_sent (
  purchase_id integer not null references purchases(id) on delete cascade,
  category text not null,
  sent_on date not null default current_date,
  primary key (purchase_id, category)
);

-- 4. Allow purchase alert categories + traceability on sms_logs
alter table sms_logs drop constraint if exists sms_logs_category_check;
alter table sms_logs add constraint sms_logs_category_check
  check (category in ('due_7','due_3','due_1','overdue','cleared','bounced','test','purchase_due','purchase_overdue'));
alter table sms_logs add column if not exists purchase_id integer references purchases(id) on delete set null;

-- 5. RLS + policies for the new tables ------------------------
alter table purchase_payments enable row level security;
alter table purchase_alerts_sent enable row level security;

drop policy if exists "Allow authenticated CRUD" on purchase_payments;
create policy "Allow authenticated CRUD" on purchase_payments
  for all to authenticated using (true) with check (true);

drop policy if exists "Allow authenticated CRUD" on purchase_alerts_sent;
create policy "Allow authenticated CRUD" on purchase_alerts_sent
  for all to authenticated using (true) with check (true);

-- 6. Default settings ----------------------------------------
insert into settings (key, value) values
  ('purchase_alert_days', '2'),   -- days before a purchase due date to send SMS (comma-separated allowed)
  ('app_base_url', '')            -- base URL used to build SMS deep links, e.g. https://app.example.com
on conflict (key) do nothing;
