-- ============================================================
-- Supplier Cheque Management System - Database Schema (PostgreSQL)
-- For execution in the Supabase SQL Editor
-- ============================================================

-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 1. Suppliers Table
create table if not exists suppliers (
  id integer generated by default as identity primary key,
  name text not null,
  contact_person text,
  phone text,
  email text,
  address text,
  bank_name text,
  bank_account_no text,
  branch_name text,
  branch_code text,
  notes text,
  is_active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Purchases Table
create table if not exists purchases (
  id integer generated by default as identity primary key,
  supplier_id integer not null references suppliers(id) on delete restrict,
  invoice_no text,
  description text,
  total_amount numeric(12, 2) not null check (total_amount > 0),
  purchase_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_purchases_supplier on purchases(supplier_id);
create index if not exists idx_purchases_date on purchases(purchase_date);

-- 3. Cheques Table
-- Cheque lifecycle: issued -> pending -> partially_paid -> cleared | bounced | cancelled
create table if not exists cheques (
  id integer generated by default as identity primary key,
  cheque_number text not null unique,
  supplier_id integer not null references suppliers(id) on delete restrict,
  amount numeric(12, 2) not null check (amount > 0),
  issue_date date not null,
  due_date date not null,
  status text not null default 'issued' check (status in ('issued','pending','partially_paid','cleared','bounced','cancelled')),
  bank_name text,
  bank_account_no text,
  branch_name text,
  branch_code text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_cheques_supplier on cheques(supplier_id);
create index if not exists idx_cheques_due on cheques(due_date);
create index if not exists idx_cheques_status on cheques(status);

-- 4. Cheque Allocations Table
-- Many-to-many bridge: how much of a cheque applies to which purchase
create table if not exists cheque_allocations (
  id integer generated by default as identity primary key,
  cheque_id integer not null references cheques(id) on delete cascade,
  purchase_id integer not null references purchases(id) on delete restrict,
  allocated_amount numeric(12, 2) not null check (allocated_amount > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_alloc_cheque on cheque_allocations(cheque_id);
create index if not exists idx_alloc_purchase on cheque_allocations(purchase_id);

-- 5. Revenue Entries Table
create table if not exists revenue_entries (
  id integer generated by default as identity primary key,
  entry_date date not null,
  amount numeric(12, 2) not null check (amount > 0),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_revenue_date on revenue_entries(entry_date);

-- 6. Savings Transactions Table
-- Running balance ledger. Balance_after makes it self-auditing.
create table if not exists savings_transactions (
  id integer generated by default as identity primary key,
  type text not null check (type in ('deposit','cheque_clearance','adjustment')),
  amount numeric(12, 2) not null,                -- positive = in, negative = out
  balance_after numeric(12, 2) not null,
  reference text,                                 -- e.g. revenue entry id / cheque number
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. SMS Logs Table
create table if not exists sms_logs (
  id integer generated by default as identity primary key,
  recipient text not null,
  message text not null,
  category text not null check (category in ('due_7','due_3','due_1','overdue','cleared','bounced','test')),
  cheque_id integer references cheques(id) on delete set null,
  status text not null default 'sent' check (status in ('sent','delivered','failed')),
  provider_ref text,
  error text,
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Alerts Sent Table (Guard to prevent duplicate reminders on daily sweep)
create table if not exists alerts_sent (
  cheque_id integer not null references cheques(id) on delete cascade,
  category text not null,
  sent_on date not null default current_date,
  primary key (cheque_id, category)
);

-- 9. Activity Logs Table
create table if not exists activity_logs (
  id integer generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null, -- Links to Supabase auth.users
  username text,                         -- Caches the email/username of the actor
  action text not null,                  -- create | update | delete | login | status_change ...
  entity_type text not null,             -- supplier | cheque | purchase | revenue | settings ...
  entity_id integer,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists idx_activity_created on activity_logs(created_at);

-- 10. Settings Table
create table if not exists settings (
  key text primary key,
  value text not null
);

-- Insert Default Settings
insert into settings (key, value) values 
  ('alert_intervals', '7,3,1'),
  ('admin_phone', '+94770000000'),
  ('currency', 'LKR'),
  ('overdue_alerts', 'true')
on conflict (key) do nothing;

-- ============================================================
-- Row Level Security (RLS) & Policies
-- ============================================================

-- Enable RLS on all tables
alter table suppliers enable row level security;
alter table purchases enable row level security;
alter table cheques enable row level security;
alter table cheque_allocations enable row level security;
alter table revenue_entries enable row level security;
alter table savings_transactions enable row level security;
alter table sms_logs enable row level security;
alter table alerts_sent enable row level security;
alter table activity_logs enable row level security;
alter table settings enable row level security;

-- Policies to allow full access only to authenticated users (admins)
create policy "Allow authenticated CRUD" on suppliers
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on purchases
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on cheques
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on cheque_allocations
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on revenue_entries
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on savings_transactions
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on sms_logs
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on alerts_sent
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on activity_logs
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated CRUD" on settings
  for all to authenticated using (true) with check (true);

